# -*- coding: utf-8 -*-
"""b2_item_reduction_v9_greedy_wrapper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tRHy7IwFGQBhKl970_NMaEo7eN4A6qf3

# Aim 2 · B2 문항축약 v9 — 그리디 래퍼(LOCO) 비정형 축소·해석

**v6~v8과의 차이 — "정형" vs "비정형"**

- v6/v7(FA 주적재량, 공통성h²)과 앞서 논의한 PCA는 전부 **문항들이 잠재요인 구조를 이룬다는 통계모형을
  먼저 가정**하고, 그 모형의 산출물(적재량)로 제거 순서를 정했습니다 — "정형(구조 가정형)" 방식.
- 이 v9는 그런 가정을 전혀 두지 않습니다. **매 스텝, 지금 남은 문항 중 하나를 실제로 빼봤을 때 leave-one
  -trial-out CV 성능이 가장 적게 나빠지는 문항을 골라 제거**합니다. 통계학에서는 이를
  **LOCO(Leave-One-Covariate-Out) importance 기반 그리디 후진소거(greedy backward wrapper / RFE)**라고
  부릅니다.
- 장점: 요인구조·선형성·정규성 같은 가정이 전혀 필요 없고, **목적함수(MAE·안전조건)에 직접 최적화**됩니다.
- 단점:
  1. **계산량이 O(문항수²)** 입니다 — 매 스텝마다 "지금 남은 문항 전부 하나씩 빼보고 CV 재평가"를 하기
     때문에, v6/v7(정해진 순서를 따라가며 스텝당 1번 평가)보다 훨씬 느립니다.
  2. **상관된 문항 쌍에서 왜곡**될 수 있습니다 — 하나를 빼도 나머지가 정보를 대신 흡수해서, 실제로는
     중요한 문항인데도 "빼도 괜찮아 보이는" 착시가 생길 수 있습니다(RF permutation importance와 같은 한계).
  3. **레벨(문항 안의 점수 구간) 해석은 안 나옵니다** — "이 문항이 중요하다"까지만 알려주고, "몇 점부터
     위험한지"는 v8(MARS 힌지)의 역할입니다.

**계산량 안내 및 속도 옵션**: 기본 실행은 **L2(빠른 solver `lbfgs`)만** 켜져 있습니다(`RUN_L2=True`,
`RUN_ELASTICNET=False`). Elastic-net은 `solver="saga"`가 필수라 같은 크기의 탐색을 몇 배 더 오래 걸리게
만들므로 기본은 꺼두었습니다 — 시간 여유가 있으면 상단 상수에서 `RUN_ELASTICNET=True`로 켜세요.
`ITEM_FLOOR`(기본 8)은 v7 결과에서 9문항 이하부터 성능이 무너지기 시작했던 것을 반영해, 그 아래까지는
굳이 탐색하지 않도록 잡은 하한선입니다.
"""

# =================================================================
# 설정 — Colab 구글드라이브
# =================================================================
from google.colab import drive
drive.mount('/content/drive')

from pathlib import Path

DATA_DIR = Path("/content/drive/MyDrive/2026 urp/preprocessed")
OUT_DIR = Path("/content/drive/MyDrive/2026 urp/outputs")
OUT_DIR.mkdir(parents=True, exist_ok=True)

BASELINE_PATH = DATA_DIR / "baseline_sample.csv"
ADL_PATH = DATA_DIR / "adl_wide.csv"

ALPHA = 0.05

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

!pip install koreanize-matplotlib -q
import koreanize_matplotlib  # 그래프 한글 깨짐 방지

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import cohen_kappa_score

TRIALS = ["AD-1061", "AD-1063", "AD-1064"]
C_DEFAULT = 0.1          # sjlee Gn 스크립트에서 중첩CV로 선택된 대표 C (v7과 동일)

# ---- 속도/탐색 범위 옵션 ----
RUN_L2 = True             # 빠름(lbfgs) — 기본 실행
RUN_ELASTICNET = False    # 느림(saga, l1_ratio=0.5) — 시간 여유 있을 때 True로
ITEM_FLOOR = 8             # 이 문항수까지만 탐색(v7에서 9문항 이하는 성능 붕괴 시작)

BADL = ["ADL0101", "ADL0102", "ADL0103", "ADL0104", "ADL0105", "ADL0106B"]
IADL = [
    "ADL0106A", "ADL0107A", "ADL0110A", "ADL0111A", "ADL0112A", "ADL0113A",
    "ADL0114A", "ADL0115A", "ADL0116A", "ADL0116B", "ADL0117A", "Q18",
    "ADL0121A", "ADL0122Q", "ADL0123L",
]
ITEMS = BADL + IADL
NI = len(ITEMS)

LAB = {"ADL0101":"Q1먹기","ADL0102":"Q2걷기","ADL0103":"Q3화장실","ADL0104":"Q4목욕","ADL0105":"Q5몸단장",
 "ADL0106B":"Q6b옷입기","ADL0106A":"Q6a옷고르기","ADL0107A":"Q7전화","ADL0110A":"Q10설거지","ADL0111A":"Q11식사준비",
 "ADL0112A":"Q12집안일","ADL0113A":"Q13빨래","ADL0114A":"Q14가전","ADL0115A":"Q15외출","ADL0116A":"Q16a쇼핑",
 "ADL0116B":"Q16b지불","ADL0117A":"Q17금전","Q18":"Q18혼자있기","ADL0121A":"Q21글쓰기","ADL0122Q":"Q22취미","ADL0123L":"Q23가전사용"}

_lines = []
def log(s=""):
    print(s)
    _lines.append(s)

"""## 1. 표본 구축 — baseline_sample + adl_wide 병합

v6~v8과 동일한 자체완결형 로직입니다.
"""

df_base = pd.read_csv(BASELINE_PATH)
df_adl = pd.read_csv(ADL_PATH)

df_base_use = df_base[df_base["in_aim1_2_sample"] == True].copy()
df_adl_base = df_adl[df_adl["VISITNUM"] == 2.0].copy()

m = df_base_use.merge(df_adl_base, on=["STUDYID", "USUBJID"], how="inner", suffixes=("", "_adl"))

Q18_SUBITEMS = ["ADL0118A__resolved", "ADL0118B__resolved", "ADL0118C__resolved"]
missing_sub = [c for c in Q18_SUBITEMS if c not in m.columns]
if missing_sub:
    print("⚠️ Q18 하위문항 중 없는 것:", missing_sub)
else:
    m["Q18"] = m[Q18_SUBITEMS].mean(axis=1)

required_cols = ITEMS + ["ds_stage", "A0_harmonized", "A1_2015_stage"]
missing_cols = [c for c in required_cols if c not in m.columns]
if missing_cols:
    print("⚠️ 다음 컬럼이 없습니다:", missing_cols)
    ITEMS = [c for c in ITEMS if c in m.columns]
    NI = len(ITEMS)
    print("→ 남은 문항수:", NI, ITEMS)

m = m.dropna(subset=["ds_stage"]).reset_index(drop=True)
before_n = len(m)
m = m.dropna(subset=["A0_harmonized"]).reset_index(drop=True)
if len(m) < before_n:
    print(f"⚠️ A0_harmonized 결측 {before_n - len(m)}건 제외 → 남은 표본 {len(m)}명")

log("# Aim 2 · B2 문항축약 v9 — 그리디 래퍼(LOCO) 비정형 축소\n")
log(f"공통표본 n={len(m)} (STUDYID별: {m['STUDYID'].value_counts().to_dict()})")
m.head()

"""## 2. 지표 함수 — mae / kappa / 중증놓침 / 비대칭분류 / 전체지표

v6~v8과 동일한 정의입니다.
"""

def mae(t, pred):
    t = np.asarray(t, dtype=float); pred = np.asarray(pred, dtype=float)
    return float(np.mean(np.abs(t - pred)))

def kap(t, pred):
    t = np.asarray(t, dtype=float); pred = np.asarray(pred, dtype=float)
    mask = ~(np.isnan(t) | np.isnan(pred))
    t = t[mask].astype(int); pred = pred[mask].astype(int)
    if len(t) == 0:
        return float("nan")
    return float(cohen_kappa_score(t, pred, weights="quadratic"))

def miss(t, pred):
    """중증놓침: 실제 4~5단계인데 예측이 4 미만으로 나온 비율."""
    t = np.asarray(t, dtype=float); pred = np.asarray(pred, dtype=float)
    mask = ~(np.isnan(t) | np.isnan(pred))
    t = t[mask]; pred = pred[mask]
    severe = t >= 4
    if severe.sum() == 0:
        return 0.0
    return float(np.mean(pred[severe] < 4))

def asym(P, t4, t5):
    """비대칭 임계값 분류: 중증(4~5단계)을 덜 놓치는 쪽으로 편향."""
    pred = np.argmax(P, axis=1).astype(float)
    p45 = P[:, 4] + P[:, 5]
    pred = np.where(p45 >= t4, 4.0, pred)
    pred = np.where(P[:, 5] >= t5, 5.0, pred)
    return pred

def metrics_all(t, pred):
    t = np.asarray(t, dtype=float); pred = np.asarray(pred, dtype=float)
    diff = pred - t
    return {
        "MAE": mae(t, pred),
        "중증놓침(%)": miss(t, pred) * 100,
        "kappa": kap(t, pred),
        "과분류(%)": (diff > 0).mean() * 100,
        "과소분류(%)": (diff < 0).mean() * 100,
        "정확일치(%)": (diff == 0).mean() * 100,
        "인접일치±1(%)": (np.abs(diff) <= 1).mean() * 100,
        "RMSE": float(np.sqrt(np.mean(diff ** 2))),
    }

"""## 3. 기준선(A0/A1) 및 CV 유틸 함수 — v7과 동일

`fit_cuts()`가 `penalty`("elasticnet"/"l2")를 명시적으로 받습니다(v7에서 고친 버전 그대로).
`penalty="l2"`일 때는 `solver="lbfgs"`로 바꿔 훨씬 빠르게 돕니다(elastic-net은 `saga` 필수).
"""

a1_mae = mae(m["ds_stage"].values, m["A1_2015_stage"].values)
a1_metrics = metrics_all(m["ds_stage"].values, m["A1_2015_stage"].values)
a0_metrics = metrics_all(m["ds_stage"].values, m["A0_harmonized"].values)
a0_miss = a0_metrics["중증놓침(%)"]

log(f"A1(2015판) 기준: MAE={a1_metrics['MAE']:.3f}, 중증놓침={a1_metrics['중증놓침(%)']:.1f}%, kappa={a1_metrics['kappa']:.3f}")
log(f"A0(2025판 조화) 기준: MAE={a0_metrics['MAE']:.3f}, 중증놓침={a0_metrics['중증놓침(%)']:.1f}%, kappa={a0_metrics['kappa']:.3f}")

class _ConstantProba:
    """희귀 절단(예: Y>=5)이 특정 fold의 훈련셋에서 전부 0(또는 전부 1)인 경우를 대비한 안전장치.
    scikit-learn 분류기와 predict_proba 인터페이스만 맞춰, 관측 비율을 그대로 반환한다."""
    def __init__(self, rate):
        self.rate = float(np.clip(rate, 1e-6, 1 - 1e-6))
    def predict_proba(self, Z):
        p1 = np.full(Z.shape[0], self.rate)
        return np.column_stack([1 - p1, p1])

def fit_cuts(Ztr, y, penalty="l2", C=C_DEFAULT):
    if penalty == "elasticnet":
        kwargs = dict(penalty="elasticnet", l1_ratio=0.5, solver="saga", C=C, max_iter=3000, tol=1e-3, random_state=0)
    elif penalty == "l2":
        kwargs = dict(penalty="l2", solver="lbfgs", C=C, max_iter=2000, random_state=0)
    else:
        raise ValueError(f"알 수 없는 penalty: {penalty}")
    models = {}
    for k in range(1, 6):
        yk = (y >= k).astype(int)
        if len(np.unique(yk)) < 2:
            models[k] = _ConstantProba(yk.mean())
        else:
            models[k] = LogisticRegression(**kwargs).fit(Ztr, yk)
    return models

def probs(models, Z):
    g = {k: models[k].predict_proba(Z)[:, 1] for k in range(1, 6)}
    P = np.zeros((Z.shape[0], 6)); P[:, 0] = 1 - g[1]
    for k in range(1, 5): P[:, k] = g[k] - g[k + 1]
    P[:, 5] = g[5]; P = np.clip(P, 1e-9, None); P /= P.sum(1, keepdims=True); return P

def tune_tau(Ptr, ds_tr, a0m):
    grid = np.round(np.arange(0.05, 0.55, 0.02), 3); best = None
    for t4 in grid:
        for t5 in grid:
            if t5 < t4: continue
            p = asym(Ptr, t4, t5)
            if miss(ds_tr, p) <= a0m + 1e-9:
                key = mae(ds_tr, p)
                if best is None or key < best[0]: best = (key, t4, t5)
    if best is None:
        c = [(miss(ds_tr, asym(Ptr, a, b)), mae(ds_tr, asym(Ptr, a, b)), a, b) for a in grid for b in grid if b >= a]
        _, _, t4, t5 = min(c); best = (0, t4, t5)
    return best[1], best[2]

def prep(m):
    folds = {}
    for ho in TRIALS:
        tri = np.array(m.index[m.STUDYID != ho]); tei = np.array(m.index[m.STUDYID == ho])
        imp = SimpleImputer(strategy="median").fit(m.loc[tri, ITEMS])
        Xtr = imp.transform(m.loc[tri, ITEMS]); Xte = imp.transform(m.loc[tei, ITEMS])
        y = m.loc[tri, "ds_stage"].astype(int).values; ds_tr = m.loc[tri, "ds_stage"].values
        a0m = miss(ds_tr, m.loc[tri, "A0_harmonized"].values)
        folds[ho] = dict(tei=tei, Xtr=Xtr, Xte=Xte, y=y, ds_tr=ds_tr, a0m=a0m)
    return folds

def eval_subset(m, folds, keep, penalty="l2", C=C_DEFAULT):
    t = m["ds_stage"].values; pred = np.zeros(len(m))
    for ho in TRIALS:
        f = folds[ho]
        sc = StandardScaler().fit(f["Xtr"][:, keep])
        mdl = fit_cuts(sc.transform(f["Xtr"][:, keep]), f["y"], penalty=penalty, C=C)
        Ptr = probs(mdl, sc.transform(f["Xtr"][:, keep])); Pte = probs(mdl, sc.transform(f["Xte"][:, keep]))
        t4, t5 = tune_tau(Ptr, f["ds_tr"], f["a0m"])
        pred[f["tei"]] = asym(Pte, t4, t5)
    return metrics_all(t, pred)

folds = prep(m)
log("폴드 준비 완료 (leave-one-trial-out ×3)\n")

"""## 4. 그리디 후진소거(LOCO wrapper) — 매 스텝 "빼도 가장 덜 아픈" 문항 제거

매 스텝: 지금 남은 문항 각각을 하나씩 실제로 빼서 `eval_subset()`으로 CV 재평가합니다.

**선택 규칙(안전조건 우선)** — 처음 버전은 MAE만 보고 후보를 골랐는데, 그러면 안전조건(중증놓침)이
계속 위반된 채로 방치될 수 있었습니다. 그래서 매 스텝:

1. 후보 중 **테스트 미스율이 A0+`safety_margin`(%p, 기본 1%p) 이내**인 것만 먼저 걸러냅니다.
2. 그 안에서 **MAE가 가장 낮은** 후보를 제거합니다.
3. 안전조건을 만족하는 후보가 하나도 없으면(전부 위반), **미스율이 가장 낮은** 후보를 제거해서 위반 폭을
   최소화하는 쪽으로 후퇴합니다.

제거할 때마다 그 순간의 ΔMAE·Δ중증놓침·Δkappa와 **어느 규칙으로 선택됐는지(선택전략)** 를 함께
기록해서, 이게 곧 "문항별 성능 기여도표"가 됩니다.

계산량: 문항수 21→8까지 내려가면 평가 횟수는 $\sum_{k=9}^{21} k = 195$번의 `eval_subset()` 호출입니다
(L2 기준 수 분, elastic-net 기준 그보다 여러 배).
"""

def greedy_backward_wrapper(m, folds, penalty="l2", C=C_DEFAULT, item_floor=ITEM_FLOOR,
                             safety_margin=1.0, log_every=1):
    # 매 스텝 후보 중 "테스트 미스율이 A0+safety_margin(%p) 이내"인 후보만 먼저 걸러내고,
    # 그 안에서 MAE가 가장 낮은(=가장 적게 나빠지는) 문항을 제거한다.
    # 안전조건을 만족하는 후보가 하나도 없으면(전부 위반) 미스율이 가장 낮은 후보를 제거해서
    # 당장의 안전조건 위반 폭이라도 최소화하는 쪽으로 후퇴한다.
    miss_limit = a0_miss + safety_margin
    keep = list(range(NI))
    met0 = eval_subset(m, folds, keep, penalty, C)
    history = [{
        "문항수": len(keep), "제거_코드": "-", "제거_라벨": "-", "선택전략": "-",
        "ΔMAE": 0.0, "Δ미스율": 0.0, "Δkappa": 0.0, **met0, "keep": list(keep),
    }]
    step = 0
    while len(keep) > item_floor:
        met_before = history[-1]
        candidates = []
        for j in keep:
            trial = [x for x in keep if x != j]
            met_try = eval_subset(m, folds, trial, penalty, C)
            candidates.append((j, met_try))

        safe = [c for c in candidates if c[1]["중증놓침(%)"] <= miss_limit + 1e-9]
        if safe:
            j_remove, met_try = min(safe, key=lambda c: c[1]["MAE"])
            strategy = "안전조건충족(MAE최소)"
        else:
            j_remove, met_try = min(candidates, key=lambda c: c[1]["중증놓침(%)"])
            strategy = "안전조건전부위반(미스율최소로후퇴)"

        code_ = ITEMS[j_remove]
        keep = [x for x in keep if x != j_remove]
        history.append({
            "문항수": len(keep), "제거_코드": code_, "제거_라벨": LAB[code_], "선택전략": strategy,
            "ΔMAE": met_try["MAE"] - met_before["MAE"],
            "Δ미스율": met_try["중증놓침(%)"] - met_before["중증놓침(%)"],
            "Δkappa": met_try["kappa"] - met_before["kappa"],
            **met_try, "keep": list(keep),
        })
        step += 1
        if step % log_every == 0:
            log(f"  [{penalty}] {len(keep)+1}→{len(keep)}문항: '{LAB[code_]}' 제거 [{strategy}] "
                f"(ΔMAE={history[-1]['ΔMAE']:+.4f}, Δ미스율={history[-1]['Δ미스율']:+.2f}%p, "
                f"미스율={met_try['중증놓침(%)']:.2f}% vs 한도{miss_limit:.2f}%)")
    return history

"""## 5. 실행 — L2(빠름, 기본 켜짐)"""

wrapper_histories = {}

if RUN_L2:
    log("\n### 그리디 래퍼 실행 — penalty=l2")
    wrapper_histories["l2"] = greedy_backward_wrapper(m, folds, penalty="l2")
    df_l2 = pd.DataFrame(wrapper_histories["l2"]).drop(columns=["keep"])
    df_l2.round(4).to_csv(OUT_DIR / "b2v9_wrapper_curve_l2.csv", index=False, encoding="utf-8-sig")
    log(f">>> 저장: {OUT_DIR / 'b2v9_wrapper_curve_l2.csv'}")
else:
    log("\n(RUN_L2=False — L2 그리디 래퍼 건너뜀)")

df_l2 = pd.DataFrame(wrapper_histories["l2"]).drop(columns=["keep"]) if RUN_L2 else None
df_l2.round(3) if df_l2 is not None else None

"""## 6. 실행 — Elastic-net(느림, 선택 — `RUN_ELASTICNET=True`일 때만)"""

if RUN_ELASTICNET:
    log("\n### 그리디 래퍼 실행 — penalty=elasticnet (시간이 오래 걸릴 수 있습니다)")
    wrapper_histories["elasticnet"] = greedy_backward_wrapper(m, folds, penalty="elasticnet")
    df_en = pd.DataFrame(wrapper_histories["elasticnet"]).drop(columns=["keep"])
    df_en.round(4).to_csv(OUT_DIR / "b2v9_wrapper_curve_elasticnet.csv", index=False, encoding="utf-8-sig")
    log(f">>> 저장: {OUT_DIR / 'b2v9_wrapper_curve_elasticnet.csv'}")
else:
    log("\n(RUN_ELASTICNET=False — 상단 상수에서 True로 바꾸면 실행됩니다)")

df_en = pd.DataFrame(wrapper_histories["elasticnet"]).drop(columns=["keep"]) if RUN_ELASTICNET else None
df_en.round(3) if df_en is not None else None

"""## 7. 곡선 시각화 + "둘다이김" 요약"""

fig, axes = plt.subplots(1, 3, figsize=(16, 4.5))
styles = {"l2": dict(marker="o", linestyle="-", color="tab:green", label="그리디 래퍼 · L2"),
          "elasticnet": dict(marker="s", linestyle="--", color="tab:red", label="그리디 래퍼 · Elastic-net")}

ax = axes[0]
for key, hist in wrapper_histories.items():
    dfk = pd.DataFrame(hist)
    ax.plot(dfk["문항수"], dfk["MAE"], **styles[key])
ax.axhline(a1_mae, color="gray", linestyle=":", label="A1 기준")
ax.invert_xaxis(); ax.set_xlabel("문항수"); ax.set_ylabel("MAE"); ax.set_title("MAE"); ax.legend(fontsize=8)

ax = axes[1]
for key, hist in wrapper_histories.items():
    dfk = pd.DataFrame(hist)
    ax.plot(dfk["문항수"], dfk["중증놓침(%)"], **styles[key])
ax.axhline(a0_miss, color="gray", linestyle=":", label="A0 기준")
ax.invert_xaxis(); ax.set_xlabel("문항수"); ax.set_ylabel("중증놓침(%)"); ax.set_title("중증놓침"); ax.legend(fontsize=8)

ax = axes[2]
for key, hist in wrapper_histories.items():
    dfk = pd.DataFrame(hist)
    ax.plot(dfk["문항수"], dfk["kappa"], **styles[key])
ax.invert_xaxis(); ax.set_xlabel("문항수"); ax.set_ylabel("가중카파"); ax.set_title("가중카파"); ax.legend(fontsize=8)

plt.tight_layout()
plt.savefig(OUT_DIR / "b2v9_wrapper_curve.png", dpi=150)
plt.show()

log("\n## 조합별 '둘다이김'(A1보다 MAE 낮고 A0+1%p 이내 중증놓침) 요약")
for key, hist in wrapper_histories.items():
    dfk = pd.DataFrame(hist)
    ok = dfk[(dfk["MAE"] < a1_mae) & (dfk["중증놓침(%)"] <= a0_miss + 1.0)]
    if len(ok):
        best_row = ok.loc[ok["MAE"].idxmin()]
        log(f"[{key}] 둘다이김 유지 최소 문항수={int(ok['문항수'].min())}, "
            f"구간 내 최저MAE 지점: 문항수={int(best_row['문항수'])}, MAE={best_row['MAE']:.3f}, "
            f"kappa={best_row['kappa']:.3f}, 중증놓침={best_row['중증놓침(%)']:.1f}%")
    else:
        log(f"[{key}] ⚠️ 둘다이김 조건을 만족하는 지점이 없습니다 (item_floor={ITEM_FLOOR}를 낮춰 더 탐색해보세요).")

"""## 8. 문항별 성능 기여도표 (LOCO 해석)

제거된 순서 자체가 "덜 중요한 것부터"이므로, **가장 나중에 제거된(=끝까지 남은) 문항일수록 중요**합니다.
각 문항이 빠질 때 기록된 ΔMAE·Δ미스율·Δkappa를 그대로 "이 문항의 성능 기여도"로 읽으면 됩니다.
"""

def build_contribution_table(hist, penalty_label):
    rows = []
    for i, h in enumerate(hist):
        if h["제거_코드"] == "-":
            continue
        rows.append({
            "패널티": penalty_label,
            "제거순번": i,                       # 낮을수록 먼저 제거 = 덜 중요
            "중요도순위(역순)": len(hist) - i,     # 높을수록 중요(오래 살아남음)
            "코드": h["제거_코드"], "라벨": h["제거_라벨"], "선택전략": h.get("선택전략", "-"),
            "제거직전_문항수": hist[i - 1]["문항수"],
            "ΔMAE": h["ΔMAE"], "Δ미스율(%p)": h["Δ미스율"], "Δkappa": h["Δkappa"],
        })
    return pd.DataFrame(rows).sort_values("중요도순위(역순)", ascending=False).reset_index(drop=True)

contribution_tables = {}
for key, hist in wrapper_histories.items():
    ctab = build_contribution_table(hist, key)
    contribution_tables[key] = ctab
    log(f"\n## 문항별 성능 기여도표 (LOCO, {key}) — 아래로 갈수록 덜 중요(먼저 제거)")
    log(ctab.round(4).to_string(index=False))
    ctab.round(4).to_csv(OUT_DIR / f"b2v9_item_contribution_{key}.csv", index=False, encoding="utf-8-sig")

first_key = "l2" if RUN_L2 else "elasticnet"
contribution_tables[first_key].round(4)

"""## 9. v7(FA 기반 4조합) 결과와 나란히 비교

직전 대화에서 확인된 v7 4조합 실측치를 그대로 하드코딩해서(재실행 시 v7 노트북의 실제 출력 csv로
교체하세요), 이번 그리디 래퍼 곡선과 같은 그래프에 겹쳐 그립니다.
"""

v7_reference = pd.DataFrame([
    {"문항수": 21, "MAE_주적재량_EN": 0.517, "MAE_주적재량_L2": 0.512, "MAE_h2_EN": 0.517, "MAE_h2_L2": 0.512},
    {"문항수": 20, "MAE_주적재량_EN": 0.518, "MAE_주적재량_L2": 0.533, "MAE_h2_EN": 0.518, "MAE_h2_L2": 0.533},
    {"문항수": 19, "MAE_주적재량_EN": 0.518, "MAE_주적재량_L2": 0.518, "MAE_h2_EN": 0.522, "MAE_h2_L2": 0.537},
    {"문항수": 18, "MAE_주적재량_EN": 0.518, "MAE_주적재량_L2": 0.547, "MAE_h2_EN": 0.521, "MAE_h2_L2": 0.552},
    {"문항수": 17, "MAE_주적재량_EN": 0.537, "MAE_주적재량_L2": 0.548, "MAE_h2_EN": 0.538, "MAE_h2_L2": 0.556},
    {"문항수": 16, "MAE_주적재량_EN": 0.553, "MAE_주적재량_L2": 0.563, "MAE_h2_EN": 0.558, "MAE_h2_L2": 0.557},
    {"문항수": 15, "MAE_주적재량_EN": 0.534, "MAE_주적재량_L2": 0.566, "MAE_h2_EN": 0.541, "MAE_h2_L2": 0.559},
    {"문항수": 14, "MAE_주적재량_EN": 0.539, "MAE_주적재량_L2": 0.568, "MAE_h2_EN": 0.543, "MAE_h2_L2": 0.559},
    {"문항수": 13, "MAE_주적재량_EN": 0.554, "MAE_주적재량_L2": 0.547, "MAE_h2_EN": 0.561, "MAE_h2_L2": 0.554},
    {"문항수": 12, "MAE_주적재량_EN": 0.576, "MAE_주적재량_L2": 0.562, "MAE_h2_EN": 0.566, "MAE_h2_L2": 0.567},
    {"문항수": 11, "MAE_주적재량_EN": 0.579, "MAE_주적재량_L2": 0.565, "MAE_h2_EN": 0.566, "MAE_h2_L2": 0.567},
    {"문항수": 10, "MAE_주적재량_EN": 0.579, "MAE_주적재량_L2": 0.576, "MAE_h2_EN": 0.579, "MAE_h2_L2": 0.566},
    {"문항수": 9,  "MAE_주적재량_EN": 0.640, "MAE_주적재량_L2": 0.633, "MAE_h2_EN": 0.604, "MAE_h2_L2": 0.595},
    {"문항수": 8,  "MAE_주적재량_EN": 0.635, "MAE_주적재량_L2": 0.627, "MAE_h2_EN": 0.602, "MAE_h2_L2": 0.584},
])

fig, ax = plt.subplots(figsize=(8, 5))
for col, style in [
    ("MAE_주적재량_EN", dict(color="tab:blue", linestyle="-", marker="o")),
    ("MAE_주적재량_L2", dict(color="tab:blue", linestyle="--", marker="o")),
    ("MAE_h2_EN", dict(color="tab:orange", linestyle="-", marker="s")),
    ("MAE_h2_L2", dict(color="tab:orange", linestyle="--", marker="s")),
]:
    ax.plot(v7_reference["문항수"], v7_reference[col], label=col.replace("MAE_", "v7·"), alpha=0.6, **style)

for key, hist in wrapper_histories.items():
    dfk = pd.DataFrame(hist)
    ax.plot(dfk["문항수"], dfk["MAE"], **styles[key], linewidth=2.5)

ax.axhline(a1_mae, color="gray", linestyle=":", label="A1 기준")
ax.invert_xaxis(); ax.set_xlabel("문항수"); ax.set_ylabel("MAE")
ax.set_title("v9 그리디 래퍼 vs v7 FA기반 4조합 (참고용 하드코딩)")
ax.legend(fontsize=7, ncol=2)
plt.tight_layout()
plt.savefig(OUT_DIR / "b2v9_vs_v7_compare.png", dpi=150)
plt.show()

"""## 10. 저장 및 해석 메모

- 그리디 래퍼는 **탐욕적(greedy)** 이라 매 스텝의 국소 최적 선택이 전체적으로 최선이라는 보장은 없습니다
  (진짜 최선의 부분집합을 찾으려면 $2^{21}$ 조합 전수조사가 필요하지만 비현실적이라 그리디로 근사).
- **상관된 문항 쌍(Q6A·Q6B)에서 왜곡 가능성**: 하나가 남아있으면 다른 하나는 "빼도 성능이 안 떨어지는"
  것처럼 보여 먼저 제거될 수 있습니다. §8 기여도표에서 이 둘의 제거 시점이 서로 붙어 있는지 확인해보세요.
- **레벨 해석이 필요하면 v8과 결합**: 이 표에서 "중요하다"로 나온 상위 문항들만 추려서, v8의 절단별
  MARS 힌지 파이프라인을 그 문항들에만 다시 돌리면 "어느 점수부터 위험한지"까지 얻을 수 있습니다.
- (여기에 실행 결과 해석을 추가하세요 — 특히 §8에서 가장 늦게 제거된 상위 5개 문항이 v6/v7의
  FA 주적재량·공통성 상위 문항과 얼마나 겹치는지, 그리고 §9 비교 그래프에서 그리디 래퍼 곡선이
  FA 기반 4조합보다 같은 문항수에서 더 낮은 MAE를 보이는 구간이 있는지 — 있다면 "목적함수에 직접
  최적화한 만큼 그리디 래퍼가 이긴다"는 근거가 됩니다.)

"""

REPORT_PATH = OUT_DIR / "b2v9_wrapper_report.md"
REPORT_PATH.write_text("\n".join(_lines), encoding="utf-8")
print(f">>> 저장: {REPORT_PATH}")

"""## 11. 외부검증 — AD-1062(그리디 래퍼 탐색에 전혀 쓰이지 않은 시험)에 1회 적용

§4~§8의 그리디 래퍼는 매 스텝 held-out CV 성능을 보고 다음에 뺄 문항을 결정했기 때문에, 그 자체로는
선택편향(더블디핑) 위험이 있습니다. 여기서는 **AD-1061/1063/1064 전체(m)로 최종 모형을 한 번만 학습**하고,
**탐색에 전혀 등장하지 않았던 AD-1062**에 **딱 한 번** 적용해서, 지금까지 본 성능이 재현되는지 확인합니다.
AIM2 Gn 스크립트의 "AD-1062 독립 외부검증"과 같은 방식입니다.
"""

EXTERNAL_STUDYID = "AD-1062"

# --- AD-1062 표본 구축 (§1과 동일 파이프라인, 대상 시험만 다름) ---
# ⚠️ baseline_sample.csv에 AD-1062가 in_aim1_2_sample=True로 안 잡혀 있을 수 있습니다(그 플래그는
#    3개 시험 공통비교표본용). AD-1062는 STUDYID로만 걸러서 씁니다. 컬럼명이 다르면 맞춰서 조정하세요.
df_adl_ext = df_adl[(df_adl["STUDYID"] == EXTERNAL_STUDYID) & (df_adl["VISITNUM"] == 2.0)].copy()
df_base_ext = df_base[df_base["STUDYID"] == EXTERNAL_STUDYID].copy()

m_ext = df_base_ext.merge(df_adl_ext, on=["STUDYID", "USUBJID"], how="inner", suffixes=("", "_adl"))

if not missing_sub:
    m_ext["Q18"] = m_ext[Q18_SUBITEMS].mean(axis=1)

m_ext = m_ext.dropna(subset=["ds_stage"]).reset_index(drop=True)
before_ext = len(m_ext)
m_ext = m_ext.dropna(subset=["A0_harmonized"]).reset_index(drop=True)
if len(m_ext) < before_ext:
    print(f"⚠️ {EXTERNAL_STUDYID} A0_harmonized 결측 {before_ext - len(m_ext)}건 제외 → 남은 표본 {len(m_ext)}명")

log(f"\n## 외부검증 표본: {EXTERNAL_STUDYID} (그리디 래퍼 탐색·학습에 전혀 미사용), n={len(m_ext)}")


def fit_final_and_validate_external(keep_idx, penalty="l2", C=C_DEFAULT, label=""):
    """m(3개 시험) 전체로 최종 모형을 한 번 학습 → m_ext(AD-1062)에 1회 적용."""
    keep_items = [ITEMS[i] for i in keep_idx]

    # 전처리 통계(중앙값 대체, 표준화)는 전부 m(학습표본)에서만 fit — m_ext 정보는 transform에만 사용
    imp = SimpleImputer(strategy="median").fit(m[keep_items])
    sc = StandardScaler().fit(imp.transform(m[keep_items]))
    Ztr = sc.transform(imp.transform(m[keep_items]))
    y = m["ds_stage"].astype(int).values
    ds_tr = m["ds_stage"].values
    a0m_full = miss(ds_tr, m["A0_harmonized"].values)

    mdl = fit_cuts(Ztr, y, penalty=penalty, C=C)
    Ptr = probs(mdl, Ztr)
    t4, t5 = tune_tau(Ptr, ds_tr, a0m_full)   # τ도 m(학습표본)에서만 튜닝

    Zte_ext = sc.transform(imp.transform(m_ext[keep_items]))
    Pte_ext = probs(mdl, Zte_ext)
    pred_ext = asym(Pte_ext, t4, t5)

    met_ext = metrics_all(m_ext["ds_stage"].values, pred_ext)
    met_a1_ext = metrics_all(m_ext["ds_stage"].values, m_ext["A1_2015_stage"].values)
    passed = (met_ext["MAE"] < met_a1_ext["MAE"]) and (met_ext["중증놓침(%)"] <= a0_miss + 1.0)

    log(f"\n## 외부검증({EXTERNAL_STUDYID}) — {label} (문항수={len(keep_items)})")
    log(f"  선택모형: MAE={met_ext['MAE']:.3f}, 중증놓침={met_ext['중증놓침(%)']:.1f}%, kappa={met_ext['kappa']:.3f}")
    log(f"  A1(2015판) 참고: MAE={met_a1_ext['MAE']:.3f}, 중증놓침={met_a1_ext['중증놓침(%)']:.1f}%, kappa={met_a1_ext['kappa']:.3f}")
    log(f"  판정: {'✅ 외부검증 통과' if passed else '❌ 외부검증 미달'} "
        f"(A1보다 MAE 낮고, 중증놓침 ≤ {a0_miss + 1.0:.2f}% 기준)")
    return dict(keep_items=keep_items, met_ext=met_ext, met_a1_ext=met_a1_ext, passed=passed)

# §5에서 만든 wrapper_histories["l2"]의 각 스텝에는 그 시점 keep(문항 인덱스 리스트)이 들어있습니다.
hist_l2 = wrapper_histories["l2"]
keep_16 = next(h["keep"] for h in hist_l2 if h["문항수"] == 16)
keep_8 = next(h["keep"] for h in hist_l2 if h["문항수"] == 8)

result_16 = fit_final_and_validate_external(keep_16, penalty="l2", label="그리디 래퍼 L2 · 16문항")
result_8 = fit_final_and_validate_external(keep_8, penalty="l2", label="그리디 래퍼 L2 · 8문항")

ext_summary = pd.DataFrame([
    {"문항수": 16, **result_16["met_ext"], "통과": result_16["passed"]},
    {"문항수": 8, **result_8["met_ext"], "통과": result_8["passed"]},
])
log("\n## 외부검증(AD-1062) 요약")
log(ext_summary.round(3).to_string(index=False))
ext_summary.round(3).to_csv(OUT_DIR / "b2v9_external_validation_AD1062.csv", index=False, encoding="utf-8-sig")

ext_summary.round(3)